import "./components/tabs"
import "./components/slider"
import "./components/burger"
import "./components/modal"
import "./components/validate"
import "./components/scrolltop"
import "./components/bookmark"
import "./components/loadmore"
