!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/main.js")}({"./src/js/components/tabs.js":
/*!***********************************!*\
  !*** ./src/js/components/tabs.js ***!
  \***********************************/
/*! no static exports found */function(module,exports){eval("var tabsBtn = document.querySelectorAll(\".hero__sidebar-link\");\nvar tabsItems = document.querySelectorAll(\".hero__content\");\ntabsBtn.forEach(onTabClick);\n\nfunction onTabClick(item) {\n  item.addEventListener(\"click\", function () {\n    var currentBtn = item;\n    var tabId = currentBtn.getAttribute(\"data-tab\");\n    var currentTab = document.querySelector(tabId);\n\n    if (!currentBtn.classList.contains('hero__sidebar-link--active')) {\n      tabsBtn.forEach(function (item) {\n        item.classList.remove('hero__sidebar-link--active');\n      });\n      tabsItems.forEach(function (item) {\n        item.classList.remove('hero__content--active');\n      });\n      currentBtn.classList.add('hero__sidebar-link--active');\n      currentTab.classList.add('hero__content--active');\n    }\n  });\n}\n\n//# sourceURL=webpack:///./src/js/components/tabs.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_tabs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./components/tabs */ "./src/js/components/tabs.js");\n/* harmony import */ var _components_tabs__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_components_tabs__WEBPACK_IMPORTED_MODULE_0__);\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});
//# sourceMappingURL=main.js.map
